#@data/values
#@overlay/match-child-defaults missing_ok=True
---
TKG_HELPER_IMAGE_REF: ""
ENABLE_TANZU_SOFTWARE_AUTO_INSTALL: false
INSTALL_CERT_MANAGER: "true"
INSTALL_CONTOUR: "false"
INSTALL_EXTERNAL_DNS: "false"
DNS_SERVER: ""
DNS_ZONE: ""
INSTALL_PROMETHEUS: "false"
INSTALL_GRAFANA: "false"
GRAFANA_PASSWORD: 
GRAFANA_FQDN: ""
INSTALL_FLUENT_BIT: "false"
MGMT_CLUSTER_NAME: ""
SYSLOG_SERVER: ""
SYSLOG_PORT: 514
SYSLOG_PROTOCOL: "udp"
SYSLOG_FORMAT: "rfc5424"
TANZU_NET_USER: ""
TANZU_NET_PASSWORD: ""
INSTALL_TBS: ""
TBS_BUNDLE: ""
TBS_REGISTRY_REPO: ""
TBS_REGISTRY_USER: ""
TBS_REGISTRY_PASSWORD: ""
TBS_REGISTRY_CA_CERT_B64: ""
INSTALL_TANZU_POSTGRES: "false"
INSTALL_TANZU_RABBITMQ: "false"
RABBITMQ_BUNDLE: ""
INSTALL_TANZU_MYSQL: "false"
INSTALL_VELERO: "false"
VELERO_S3_ACCESS_KEY: ""
VELERO_S3_SECRET_KEY: ""
VELERO_S3_BUCKET_NAME: ""
VELERO_S3_REGION: "minio"
VELERO_S3_URL: ""

