---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.1.0+vmware.1-tkg.2
      prereleases: {}
  serviceAccountName: tkg-packages-sa
